### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by valdier1** [edzillion/blood-n-guts#78]
After the latest update I now get an error anytime a scene loads

blood-n-guts |  drawSplats: splatStateObj.tokenId
foundry.js:10020 TypeError: Cannot read property 'data' of null
    at lookupTokenBloodColor (helpers.js:104)
    at new SplatToken (SplatToken.js:22)
    at Token.<anonymous> (blood-n-guts.js:455)
    at Generator.next (<anonymous>)
    at fulfilled (blood-n-guts.js:11)
draw @ foundry.js:10020

**Comment by valdier1** [comment]
![2020-11-03 11_30_34-Keep on the Hill • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/13425341/98032870-7f853380-1dc9-11eb-852c-6239cad2d8b3.png)

**Comment by edzillion** [comment]
Thanks for the report @valdier1 

I am having trouble reproducing this. Looking at your error there the logs seem like they're from an older version. 

`blood-n-guts | drawSplats: splatStateObj.tokenId` should read: `blood-n-guts |  tokenSplat: draw`

https://github.com/edzillion/blood-n-guts/blob/8de951156d29f1f6c082991b74d567f698ebf5a8/src/module/SplatToken.ts#L354

I tried to recreate with version 0.5.13 and this is what I got:

```js
blood-n-guts |  lookupTokenBloodColor:  Ogre npc Giant 
blood-n-guts |  lookupTokenBloodColor getRGBA: blood rgba(138, 7, 7, 0.7)
blood-n-guts |  lookupTokenBloodColor: rgba(138, 7, 7, 0.7)
[...]
blood-n-guts |  tokenSplat: draw 2
Foundry VTT | Rendering HeadsUpDisplay
```

The issue itself seems like an async problem. I wonder is it caused by a conflict with another mod?

**Comment by edzillion** [comment]
I have just pushed v0.5.14 so you can just update to that one.

**Comment by valdier1** [comment]
> I have just pushed v0.5.14 so you can just update to that one.

Ok, I updated to 0.5.14 but am still seeing the same. I am going to remove the module completely and reinstall it just in case there is something outstanding

**Comment by valdier1** [comment]
I'm not seeing a change, but here is an expanded log

![image](https://user-images.githubusercontent.com/13425341/98038593-3b4a6100-1dd2-11eb-9637-ee6ccadd0cb4.png)

**Comment by valdier1** [comment]
I'm thinking this isn't an issue with BNG, but actually with another module now that I look deeper, I will close this out
