### ISSUE TITLE
Canvas drawing failed for Token Layer

### ISSUE THREAD

**Issue by amcvfx** [edzillion/blood-n-guts#99]
Hey! I've been getting this error with Blood 'n Guts enabled.
![image](https://user-images.githubusercontent.com/35099081/98691156-a44b4f00-2365-11eb-8368-06adc91b809f.png)

I'm not sure if it's causing any issues but I thought I should flag it.

**Comment by edzillion** [comment]
Thanks for the report @amcvfx !

Does it come up every time? I have seen this issue happening when using with other mods that effect Tokens. e.g. Token Aura, CUB (I have heard). 

Do you have anything like that running at the same time? Also when this next happens can you press F12 and have a look if there is an error in the console logs?

**Comment by amcvfx** [comment]
Yes I have found I get the error when only Blood n Guts is active (I used Find the Culprit). Here is the error I think. I'm using 0.6.1.

![image](https://user-images.githubusercontent.com/35099081/98794435-f7261480-2400-11eb-85e6-fd248f6243cc.png)

**Comment by edzillion** [comment]
Fixed in the latest v0.6.3 @amcvfx - please test if you get the chance. #103

**Comment by amcvfx** [comment]
Thanks for looking into it! It seems the error still exists though.

![image](https://user-images.githubusercontent.com/35099081/98873984-499f1980-2471-11eb-95e9-04cc81fd1c0c.png)

**Comment by edzillion** [comment]
Ok version 0.6.4 should log the error and return the default blood color instead of crashing. You will probably still get an error, can you post it here? Should start with `blood-n-guts | lookupTokenBloodColor missing actor data for token`

**Comment by amcvfx** [comment]
I got this error but not sure if it's related?
![image](https://user-images.githubusercontent.com/35099081/98995902-f1781e00-2529-11eb-9f1e-f8716deb5b2d.png)

**Comment by edzillion** [comment]
It's not but I am pretty sure #107 0.6.5 will have fixed that one too 🤞

**Comment by amcvfx** [comment]
Nice that seems to have fixed it!

**Comment by edzillion** [comment]
Great. I will close this now. Prepping for full release today, if nothing else comes up 🤞
